language: rust
os:
  - linux
  - osx
rust:
  - nightly
  - nightly-2016-05-17 # Should be kept in sync with Servo.
matrix:
  allow_failures:
    - rust: nightly
notifications:
  webhooks: http://build.servo.org:54856/travis
addons:
  apt:
    packages:
      - libgles2-mesa-dev
