[package]
name = "directcomposition"
version = "0.1.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]

[dependencies]
gl = "0.6.0"
glutin = "0.12"
winapi = {version = "0.3", features = ["winerror", "d3d11", "dcomp"]}
wio = "0.2"
