[package]
name = "webrender_traits"
version = "0.1.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]

[dependencies.offscreen_gl_context]
git = "https://github.com/ecoal95/rust-offscreen-rendering-context"

[dependencies.ipc-channel]
git = "https://github.com/servo/ipc-channel"

[dependencies]
app_units = {version = "0.2.1", features = ["plugins"]}
euclid = {version = "0.6.2", features = ["plugins"]}
gleam = "0.2"
serde = {version = "0.6", features = ["nightly"]}
serde_macros = "0.6"

[target.x86_64-apple-darwin.dependencies]
core-graphics = "0.2"
