[package]
name = "webrender"
version = "0.1.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]

[dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[dependencies.webrender_traits]
git = "https://github.com/glennw/webrender_traits"

[dependencies]
gleam = "*"
euclid = "0.3"
time = "*"
fnv="*"
scoped_threadpool = "0.1.6"
app_units = "0.1"
lazy_static = "0.1"
simd = { git = "https://github.com/huonw/simd" }

[target.x86_64-apple-darwin.dependencies]
core-graphics = "*"
core-text = "*"

