[configs]
skip-check-length = false
skip-check-licenses = false

[ignore]

# Files that are ignored for all tidy and lint checks.
files = [
    # servo-tidy does not properly support workspaces yet.
    "./Cargo.toml",
    # There are many duplicated packages, which we probably need to review one by one.
    "./Cargo.lock",
    # We need to ensure that tidy's suggested options are okay for this script.
    "./wrench/test.sh",
]

# Many directories are currently ignored while we tidy things up
# gradually.
directories = [
   # Generated and upstream code combined with our own. Could use cleanup
  "./target",
  "./webrender",
]
